### ISSUE TITLE
hood create:config fails db/config.json doesn't already exist

### ISSUE THREAD

**Issue by justinbarry** [eaigner/hood#52]
``` bash
$ /bin/hood create:config
panic: open /Users/justin/repos/goHood/db/config.json: no such file or directory

goroutine 1 [running]:
main.init·1()
    /usr/local/go/src/pkg/github.com/eaigner/hood/cmd/cmd.go:56 +0x54c
main.init()
    /usr/local/go/src/pkg/github.com/eaigner/hood/cmd/templates.go:5 +0xf9

goroutine 2 [syscall]:
created by runtime.main
    /usr/local/go/src/pkg/runtime/proc.c:221
```

**Comment by eddytrex** [comment]
I confirm this issue even if  the db/config.json is created manually

**Comment by eaigner** [comment]
Whoops, there seems to be a regression there. I recently rewrote the hood commandline tool.
